<a href="https://colab.research.google.com/github/sivasaiyadav8143/Deep-Learning-with-Python/blob/main/Linear_Algebra_with_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 
Numpy is a Linear Algebra Library in Python.It provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

[More On](https://numpy.org/doc/stable/user/whatisnumpy.html)

In [2]:
# importing numpy
import numpy as np

In [3]:
print(np.__version__)

1.18.5


With numpy we can vectors which is a 1-d arrays and matrices are 2-d.We can perform all operations that we do in mathematics. Lets see ony by one with numpy.

### Create a vector or 1D array and a matrix or 2D array

In [7]:
# vector = np.array([0,1,2,3,4,5,6,7])
vector = np.arange(8)
vector

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
matrix = np.array([[0,1,2],[3,4,5],[6,7,8]])
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Array Slicing

In [14]:
mat1 = np.arange(25)
print(mat1) # vector

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [16]:
mat1 = mat1.reshape(5,5) # conveting or reshaping a vector to a 5*5 matrix
mat1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
# Note : Indexing starts from 0, not from 1

print(mat1[0,0]) # 1st row, 1st column
print('\n')
print(mat1[1,4]) # 2nd row, 5th column
print('\n')
print(mat1[2][2]) # 3rd row, 3rd column
print('\n')
print(mat1[4][0]) # 5th row, 1st column
print('\n')
print(mat1[:,0]) # all row of 1st column
print('\n')
print(mat1[2,:]) # 3rd row, all column

0


9


12


20


[ 0  5 10 15 20]


[10 11 12 13 14]


In [34]:
print(mat1[4,:3]) # 5th row, 1,2,3 columns
print('\n')
print(mat1[1:4,0]) # 2,3,4 rows of 1st column
print('\n')
print(mat1[1:4,1:4]) #  2,3,4 rows of 2,3,4 columns (subsetmatrix)

[20 21 22]


[ 5 10 15]


[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


Basic Array operations

In [37]:
print(type(mat1)) #datatype of mat1
print('\n')
print(mat1.shape) # rows x columns of mat1
print('\n')
print(mat1.dtype) #datatype of elements in mat1
print('\n')
print(mat1.ndim) # number of dimensions
print('\n')
print(mat1.size) #number of Elements in mat1

<class 'numpy.ndarray'>


(5, 5)


int64


2


25


In [48]:
print(mat1.max()) #max val in mat1
# print(np.max(mat1)) # another way

print('\n')

print(mat1.argmax()) #index of max val in mat1
# print(np.argmax(mat1)) # another way

print('\n')

print(mat1.min()) #min val in mat1
# print(np.min(mat1)) # another way

print('\n')

print(mat1.argmin()) #index of min val in mat1
# print(np.argmin(mat1)) # another way

print('\n')

print(mat1.sum()) #sum of all mat1 values
# print(np.sum(mat1)) # another way

print('\n')

print(mat1.cumsum()) #cummulative sum of all mat1 values
# print(np.cumsum(mat1)) # another way

24


24


0


0


300


[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276 300]


### Basic Arithmetic operations

In [49]:
mat1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
# lets create two sub-matrix
sub_mat1 = mat1[:3,:3] # first 3 rows with first 3 columns
sub_mat2 = mat1[2:,2:] # last 3 rows with last 3 columns
print(sub_mat1)
print('\n')
print(sub_mat2)

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


[[12 13 14]
 [17 18 19]
 [22 23 24]]


In [64]:
print(sub_mat1 + sub_mat2) # addition of two matrix
# print(np.add(sub_mat1,sub_mat2))  # another way

print('\n')

print(sub_mat1 - sub_mat2) # substraction of two matrix
# print(np.subtract(sub_mat1,sub_mat2))  # another way

print('\n')

# you can only multiply 2 matrices whose no.of columns in 1st matrix == no.of rows in  2nd matrix
print(sub_mat1 * sub_mat2) # multiplication of two matrix
# print(np.multiply(sub_mat1,sub_mat2))  # another way

print('\n')

print(sub_mat1 / sub_mat2) # division of two matrix
# print(np.divide(sub_mat1,sub_mat2))  # another way

print('\n')

print(sub_mat1 ** sub_mat2) # power of matrix
# print(np.power(sub_mat1,sub_mat2))  # another way

print('\n')

print(sub_mat1 > sub_mat2) # greater than operator
# print(np.greater(sub_mat1,sub_mat2))  # another way

print('\n')

print(sub_mat1 >= sub_mat2) # greater than or wqual to operator
# print(np.greater_equal(sub_mat1,sub_mat2))  # another way

print('\n')

print(sub_mat1 < sub_mat2) # less than operator
# print(np.less(sub_mat1,sub_mat2))  # another way

print('\n')

print(sub_mat1 <= sub_mat2) # less than or wqual to operator
# print(np.less_equal(sub_mat1,sub_mat2))  # another way


[[12 14 16]
 [22 24 26]
 [32 34 36]]


[[-12 -12 -12]
 [-12 -12 -12]
 [-12 -12 -12]]


[[  0  13  28]
 [ 85 108 133]
 [220 253 288]]


[[0.         0.07692308 0.14285714]
 [0.29411765 0.33333333 0.36842105]
 [0.45454545 0.47826087 0.5       ]]


[[                   0                    1                16384]
 [        762939453125      101559956668416    11398895185373143]
 [ 1864712049423024128  6839173302027254275 -5124814900970913792]]


[[False False False]
 [False False False]
 [False False False]]


[[False False False]
 [False False False]
 [False False False]]


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


NOTE : The operation we performed above is not matrix multiplication, in numpy it's element wise multiplication, thats why it did not throw an error.

In [65]:
# to perform matrix multiplication, use dot() in numpy
sub_mat1.dot(sub_mat2)

array([[ 61,  64,  67],
       [316, 334, 352],
       [571, 604, 637]])

### Basic Filer operations

In [68]:
mat1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
print(mat1[mat1 > 15]) # filter values > 15

print('\n')

print(mat1[mat1 % 2 == 0]) #even numbers in mat1

print('\n')

print(mat1[mat1 % 2 != 0]) #odd numbers in mat1

print('\n')

print(mat1[(mat1 % 3 == 0) & (mat1 % 5 == 0)]) # values divisible by 3 and 5

[16 17 18 19 20 21 22 23 24]


[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


[ 1  3  5  7  9 11 13 15 17 19 21 23]


[ 0 15]


In [66]:
# Transpose of a matrix i.e. switching/interchange rows and columns.
mat1.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [67]:
np.transpose(mat1)

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])