In [2]:
from random import choice
from numpy import array, dot, random

import numpy as np


In [ ]:
# MCNeuron for AND Gate
# In MCNeuron, there is no concept of weights, all the inputs are given same importance.
w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]), 0),
    (array([1,0]), 0),
    (array([1,1]), 1),
]

step_function = lambda x: 0 if x < 2 else 1    # Step function with threshold of 2. Anything below is 0 

In [ ]:
for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 0
[1 0]: 1.0 -> 0
[1 1]: 2.0 -> 1


In [ ]:
# MCNeruon for OR
w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]), 1),
    (array([1,0]), 1),
    (array([1,1]), 1),
]

step_function = lambda x: 0 if x < 1 else 1    # Step function with threshold of 1. Anything below is 0 


In [ ]:
for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 1


In [ ]:
# MCNeuron for NAND

step_function = lambda x: 0 if x >= 2 else 1    # Step function with threshold of > 2 is 0 

w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 1),
    (array([0,1]), 0),
    (array([1,0]), 0),
    (array([1,1]), 0),
]

for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 1
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 0


In [ ]:
# The problem with MCN is, we manually has to adjust the weights.
# Rosenblat's Perceptron included a way to adjust the weights and find the appropriate combinations 
# to overcome the need to modify thresholds for each gate separately, it used a bias term using which the thresholds in the 
# neuron can be modified to implement multiple Boolean functions in one code

In [6]:
step_function = lambda x: 0 if x < 30 else 1

training_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 0),
    (array([1,0,1]), 0),
    (array([1,1,1]), 1),
]

w = random.rand(3)
print(f' before loop, W : {w}')
b = .1    # initializing bias term
errors = []
eta = 0.1
n = 10

for i in range(n):
    x, expected = choice(training_data)
    print(f'X : {x}')
    
   # w = np.append(w, b)

    result = dot(w, x)
    error = expected - step_function(result)   # irrespective of what threshold we set, the algo will find the approp weights
    print(f'Error, {error}')
    errors.append(error)                       # that is the beauty of bias. The 'AND' pattern is learnt from data
    w += eta * error * x
    print(f' In loop, W : {w}')

 before loop, W : [0.7784629  0.94180421 0.5953995 ]
X : [1 0 1]
Error, 0
 In loop, W : [0.7784629  0.94180421 0.5953995 ]
X : [0 0 1]
Error, 0
 In loop, W : [0.7784629  0.94180421 0.5953995 ]
X : [1 1 1]
Error, 1
 In loop, W : [0.8784629  1.04180421 0.6953995 ]
X : [0 1 1]
Error, 0
 In loop, W : [0.8784629  1.04180421 0.6953995 ]
X : [0 0 1]
Error, 0
 In loop, W : [0.8784629  1.04180421 0.6953995 ]
X : [1 1 1]
Error, 1
 In loop, W : [0.9784629  1.14180421 0.7953995 ]
X : [0 0 1]
Error, 0
 In loop, W : [0.9784629  1.14180421 0.7953995 ]
X : [0 1 1]
Error, 0
 In loop, W : [0.9784629  1.14180421 0.7953995 ]
X : [0 0 1]
Error, 0
 In loop, W : [0.9784629  1.14180421 0.7953995 ]
X : [1 1 1]
Error, 1
 In loop, W : [1.0784629  1.24180421 0.8953995 ]


In [ ]:

step_function = lambda x: 0 if x < 30 else 1    # Step function with threshold of 0.5. Anything below is 0 


training_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 0),
    (array([1,0,1]), 0),
    (array([1,1,1]), 1),
]

w = random.rand(3)
b = .1    # initializing bias term
errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = choice(training_data)
    
   # w = np.append(w, b)

    result = dot(w, x)
    error = expected - step_function(result)   # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                       # that is the beauty of bias. The 'AND' pattern is learnt from data
    #when error is there will not be any update in weights since whole expression will become zero and old weight remains.
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))


In [ ]:
# OR function in RB Neuron


step_function = lambda x: 0 if x < 10 else 1    # Step function with threshold of 0.5. Anything below is 0 


# AND gate
training_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]

w = random.rand(3)
b = .1    # initializing bias term
errors = []
eta = 0.01
n = 10000

for i in range(n):
    x, expected = choice(training_data)
    
   # w = np.append(w, b)

    result = dot(w, x)
    error = expected - step_function(result)   # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                       # that is the beauty of bias. The 'OR' pattern is learnt from data
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))


[0 0 1]: 6.261557703740946 -> 0
[0 1 1]: 10.363693189499358 -> 1
[1 0 1]: 10.000889576025322 -> 1
[1 1 1]: 14.103025061783736 -> 1
